audit_header: false
title: DFW Real Estate
description: Our mission at The Maddern Team is to be your best resource for Plano real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Maddern Team, your professional Plano Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jessica and Brad Maddern
  title:
  license_number:
  about_markdown: |
    The Maddern Team is made up of Jessica and Brad Maddern and their team of expert real estate professionals. Jessica Maddern, named rookie of the year at Keller Williams Plano, a market center in the heart of the Dallas Fort Worth Metroplex with over 400 agents. She is a former member of the Agent Leadership Council at the Plano market center. She has also been named a 2018 Five Star Rising Star Professional and Best of D Magazine 2018 and 2019. Brad, a native of Michigan, attended Central Michigan University and earned his undergraduate degree in Commercial Recreation. Brad spent more than seven years managing professional golf events with the PGA Championships and events on The PGA Tour including The Byron Nelson Championship in Dallas. Brad also has extensive experience with project management and operations both in the golf and construction business.
  brand: The Maddern Team
  brokerage: Keller Williams Plano
  market: Plano
  address: 3600 Preston Rd. Plano, TX 75093
  phone: 469-649-7077
  phone_type:
  phone2:
  phone2_type:
  email: TheMaddernTeam@kw.com
  url: http://TheMaddernTeam

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://cloudcma.com/api_widget/013e97988b6f1f1dbeb477f9018b8f31/show?post_url=cloudcma.com&source_url=ua
  second_CTA_text: Home Search
  second_CTA_URL: https://themaddernteam.kw.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Plano Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://cloudcma.com/api_widget/013e97988b6f1f1dbeb477f9018b8f31/show?post_url=cloudcma.com&source_url=ua

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Plano Home?"
    CTA_text2: "Search the entire MLS for your Plano home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://themaddernteam.kw.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheMaddernTeam/
  linkedin_url: https://www.linkedin.com/in/jessicaharbinmaddern/
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/themaddernteam/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Plano Real Estate Podcast with Jessica and Brad Maddern'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Plano Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Maddern Team - your professional Plano Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Plano, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jessica and Brad Maddern'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: DFW Real Estate
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#963CBD'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#963CBD'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
